kind = "mobile"
previewPath = "/mobile/"
title = "Students of Islamic Law Mobile"
version = "1.0.0"
id = "artifacts/students-forum-mobile"
router = "path"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 8099

[services.development]
run = "pnpm --filter @workspace/students-forum-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/students-forum-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/students-forum-mobile", "run", "serve" ]

[services.env]
PORT = "8099"
BASE_PATH = "/mobile/"
